# Generated by Django 4.0.4 on 2022-05-15 02:36

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(verbose_name='Vídeo'),
        ),
    ]
