# Generated by Django 4.0.4 on 2022-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
