# Generated by Django 4.0.5 on 2022-06-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_lessonrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrelation',
            name='course',
        ),
    ]
