# Generated by Django 4.0.5 on 2022-06-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_remove_lessonrelation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_duration',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
    ]
