# Generated by Django 4.0.4 on 2022-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
