# Generated by Django 4.0.4 on 2022-05-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_file_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
    ]
