# Generated by Django 4.0.5 on 2022-06-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='text',
            name='owner',
        ),
    ]
