# Generated by Django 4.0.5 on 2022-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
