# Generated by Django 4.0.5 on 2022-06-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
