# Generated by Django 4.0.5 on 2022-06-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_comment_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(verbose_name='Avaliação'),
        ),
    ]
