# Generated by Django 4.0.5 on 2022-06-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_rating_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['created']},
        ),
    ]
