# Generated by Django 4.0.5 on 2022-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learn_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
