# Generated by Django 4.0.5 on 2022-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_learn_description_course_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='profiles/', verbose_name='Imagem'),
        ),
    ]
