# Generated by Django 4.0.5 on 2022-06-08 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_remove_course_owner_course_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='courses_own', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='learn_description',
            field=models.TextField(verbose_name='Descrição de aprendizado'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(verbose_name='Requirementos para o curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(verbose_name='Descrição curta'),
        ),
    ]
