# Generated by Django 4.0.4 on 2022-05-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_created_question_updated_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
