# Generated by Django 4.0.4 on 2022-05-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_answer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
