# Generated by Django 4.0.4 on 2022-05-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id']},
        ),
    ]
