# Generated by Django 4.0.4 on 2022-06-02 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0005_alter_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='questions_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
