# Generated by Django 4.0.4 on 2022-06-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_question_likes_question_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
